/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Background: typeof import('./components/styles/Background.vue')['default']
    CardRooms: typeof import('./components/system/CardRooms.vue')['default']
    CircleRooms: typeof import('./components/system/CircleRooms.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    Lander: typeof import('./components/system/Lander.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    NavBar: typeof import('./components/common/NavBar.vue')['default']
    Profiles: typeof import('./components/system/Profiles.vue')['default']
    RegisterFor: typeof import('./components/auth/RegisterFor.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RoomSuggest: typeof import('./components/system/RoomSuggest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./components/common/ScrollDown.vue')['default']
  }
}
